stages:
  - build

before_script:
  - apt update -y && apt install git -y
  - git clone https://github.com/TheThingsNetwork/lora_gateway.git
  # Creating release path
  - mkdir release
  - export RELEASE_PATH="$PWD/release"

multitech-conduit-golang:
  stage: build
  image: registry.gitlab.com/thethingsnetwork/packet_forwarder/multitech-toolchain
  script:
    - export CFG_SPI=ftdi
    - export PLATFORM=multitech
    - pushd go
    # Go build environment variables
    - export GOROOT=$PWD/go
    - export GOPATH=$PWD/gopath
    - export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
    # Downloading go if not installed yet
    - apt install make git tar wget libftdi-dev -y
    - apt-get install wget -y && wget https://storage.googleapis.com/golang/go1.8.1.linux-amd64.tar.gz && tar -C $PWD -xvzf go1.8.1.linux-amd64.tar.gz
    # Enable mLinux toolchain
    - sdk_enable_file=$(ls /opt/mlinux/*/*setup*)
    - source $sdk_enable_file
    # Compile libloragw
    - pushd ../lora_gateway/libloragw
    - make all
    - popd
    # Go to packet forwarder file
    - CGO_ENABLED=1 GOARCH=arm GOARM=5 go build -o benchmark -v
    - cp benchmark "$RELEASE_PATH"
    - popd
  artifacts:
    paths:
      - release/
